resource:
  - name: source-code
    type: git
    source:
      uri: https://github.com/j3tchy/price-stalker.git
      branch: ((branch))

jobs:
  - name: install-dependencies
    plan:
      - in_parallel:
        - get: source-code
          trigger: true
      - task: install-dependencies
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "16"
          run:
            path: /bin/sh
            dir: source-code
            args:
              - -c
              - |
                ls -la