resources_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: source-code
    type: git-branches
    source:
      uri: https://github.com/j3tchy/price-stalker.git
  
  - name: concourse-pipelines
    type: git
    source:
      uri: https://github.com/j3tchy/concourse-pipelines.git

jobs:
  - name: set-feature-pipelines
    plan:
      - in_parallel:
        - get: source-code
          trigger: true
        - get: concourse-pipelines
      - load_var: branches
        file: source-code/branches.json
      - across:
        - var: branch
          values: ((.:branches))
        set_pipeline: dev
        file: concourse-pipelines/generic-git-branches.yml
        instance_vars: { feature: ((.:branch.groups.feature ))}
        vars: { branch: ((.:branch.name)) }